### ISSUE TITLE
Dump sample images to disk

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/TrackerboxReloaded#20]
As a debugging thing, dump images every 10? seconds to the Pi's hard drive, or a USB stick so we can analyze after a match what the vision camera was seeing and if it needs to be re-calibrated.

We would need to A) detect if the USB stick is inserted, then dump:
- properties file (only on start-up?)
- raw image
- binary mask

(credit to Brian for the idea!)

**Comment by ounsworth** [comment]
Wait, why is this done?

**Comment by thatmadhacker** [comment]
I implemented this and I believe it is on master

**Comment by ounsworth** [comment]
Cool!
Also, really? Have you solved the USB stick part of the problem?

**Comment by thatmadhacker** [comment]
Yes, simply mount the usb to a folder and set the output for to that folder

**Comment by ounsworth** [comment]
Cool. Let's go over that code together at tomorrow's meeting.

-Mike
