### ISSUE TITLE
Make it analyse images

### ISSUE THREAD

**Issue by MatEdwards** [FRC2706/TrackerboxReloaded#4]
Look at past code and attempt to analyse a image using the same sort of commands. May want to communicate with person doing calculations to figure out best commands to use

**Comment by ounsworth** [comment]
Design an opencv filter pipeline.

**Comment by ounsworth** [comment]
Proposed pipeline:
- [ ] Yellow threshold (& B&W cleanup like erode/dilate) --> Binary Mask
- [ ] extractContours() --> list of non-touching objects
- for each contour (object):
  - [ ] Apply binary mask to colour img with ROI bounding box from contor
  - [ ] toGrayscale()
  - [ ] cleanup ?
  - [ ] Canny edge detect & Corner detect

(we may find that we don't need the corners, the centre of each cube blob might be enough, so we could stop at the extractContours() step)
