### ISSUE TITLE
Finish linux scripts

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/TrackerboxReloaded#42]

**Comment by thatmadhacker** [comment]
Finished Linux things, they work fixed servicey things

**Comment by thatmadhacker** [comment]
readlized we havent finished it

**Comment by thatmadhacker** [comment]
Finished it, this time it works, we did servicey things and made them work

**Comment by thatmadhacker** [comment]
Realized w ewernt done

**Comment by thatmadhacker** [comment]
Fixed linux scripts, added uninstall script
