### ISSUE TITLE
Pi system clock doesn't work: re-think img name timestamps

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/TrackerboxReloaded#56]
Brian found that one of the ways Pis keep their cost down is no battery to keep time consistently across reboots. This means that using the datetime as part of the file name, or sorting by modification time, is no good.

Possibly solution:
- Use an incrementing integer in the file name; on file write, look for the highest numbered file in the folder and +1 to it.
- Put that number first in the file name (rather than "raw", "binary", "output") so that we can properly sort by filename and the triplets group properly.

**Comment by thatmadhacker** [comment]
Done
