### ISSUE TITLE
Spec: decide which camera

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/TrackerboxReloaded#6]
Pi ribbon vs USB camera (lifecam 3000) vs ethernet

We need to do some testing on the pi ribbon camera / USB camera and decide if it's good enough. Questions include (but are not limited to):

- Does the Pi camera do annoying things like auto-whitebalance? (some googling will probably answer this)
- What's the colour depth like on the ribbon camera? Is it "rich" enough? (probably need to look at the two camera feeds side-by-side).
- What's the overall quality of the image like (sharpness, lens distortion, etc)?
- How bad is motion blur on the ribbon camera? ( can probably google "rolling shutter" vs "full-frame". We can probably come up with a way to test it, take a still while waving it around).
- Other relevant questions?

**Comment by TMSD** [comment]
Pi camera Works with pi zero running trackerbox 2 Internal camera Setting at 4-5 fps.

Steps to use:
1. Install Trackerbox2 on pi
2. Enable camera in raspi-config
3. Set Trackerbox2 to Setting 3 (internal Laptop Camera)
4.Make
5. ./trackerbox2

If Segmentation fault, make sure you Have the camera enabled and reboot the pi.
